AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CmdParms:
    Type: Number
    Default: 10
Resources:
  RunCommand:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command:
        Fn::Sub: |
          sudo yum install git -y
          yum install -y python3 python3-pip >> /command-output.txt
          git clone https://github.com/themarcoszone/latam_challenge.git >> /command-output.txt
          cd latam_challenge 
          pip install requirements.txt  >> /command-output.txt
          cd src/
          python3 q1_memory.py >> /command-output.txt
          echo "SUCCESS" >> /command-output.txt
      Role: marcos-ec2-s3
      LogGroup: my-cloudwatch-log-group

Outputs:
  Output:
    Description: Data Eng Challenges
    Value:
      Fn::GetAtt: RunCommand.Output